### ISSUE TITLE
Failed to Ping My Local Router?

### ISSUE THREAD

**Issue by hc128168** [Goutam1511/Socket-Programming-with-C#1]
Hi,

I tried to run with arguments "192.168.1.1 192.168.1.8", .1 is my router IP and .8 is my local IP.

When I run, it prints, "Packet Sending Failed!".  Then I modified your code to print out `strerror(errno)`.  The string is `No such device or address`.

Any idea?

**Comment by Goutam1511** [comment]
Which program are you getting this error at?

**Comment by hc128168** [comment]
My bad.  I am referring to [myping.c](https://github.com/Goutam1511/Socket-Programming-with-C/blob/master/myping.c)

**Comment by Goutam1511** [comment]
Are you filling the Source and Destination MAC properly? For my program, these are hardcoded. Can you provide the packet capture of your network interface?

**Comment by hc128168** [comment]
Oh, I didn't realize you hardcoded the MAC.  Thanks for pointing out  the issue.
